AllCops:
  RunRailsCops: true
  Exclude:
    - bin/*
    - Guardfile
    - vendor/**/*
    - lib/tasks/**/*
    - chef/**/*
Metrics/AbcSize:
  Exclude:
    - app/models/tweet_decorator.rb
    - app/models/tweeter_decorator.rb
Metrics/LineLength:
  Max: 120
  Exclude:
    - app/models/gnip_client.rb
Metrics/MethodLength:
  Max: 12
  Exclude:
    - app/models/tweet_decorator.rb
    - app/models/tweeter_decorator.rb
Rails/TimeZone:
  Enabled: false # it's a good idea, but currently broken
Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - before
    - given
    - given!
    - let
    - let!
    - subject
    - times
    - try
Style/Documentation:
  Enabled: false
Style/FileName:
  Exclude:
    - lib/gnip-stream.rb

