AllCops:
  RunRailsCops: true
  Exclude:
    - Guardfile
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 14
Rails/TimeZone:
  Enabled: false # it's a good idea, but currently broken
Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - before
    - given
    - given!
    - let
    - let!
    - subject
    - times
    - try
Style/Documentation:
  Enabled: false
Style/FileName:
  Exclude:
    - lib/gnip-stream.rb
